### ISSUE TITLE
View Development of Main Page

### ISSUE THREAD

**Issue by yujiah-github** [yujiah-github/MovieApp#2]
- [ ] View Development of Main Page
- [ ] Add Movie Open API

**Comment by yujiah-github** [comment]
- [ ] Add View Styles
